### PR TITLE
Cache docker build in GHA

### PR DESCRIPTION
**Pull request by Jomik**

### CODE REVIEW

**Review by AlinaNova21 — APPROVED** [review]

**Comment by tedivm** [comment]
You should never use a cache in a docker build process, you should only use it for local development. Caching on the build layer means you don't get security and bugfixes because you're using cached versions. If your cache doesn't clear for a year then you're using software that hasn't been updated in a year.

**Comment by Jomik** [comment]
> You should never use a cache in a docker build process, you should only use it for local development. Caching on the build layer means you don't get security and bugfixes because you're using cached versions. If your cache doesn't clear for a year then you're using software that hasn't been updated in a year.

Are you sure? The cache is invalidated if the step changes, right? So if a `package-lock.json` updates, the step, and subsequent steps would be invalidated.
Which steps would you worry about being cached here?

**Comment by tedivm** [comment]
Everything in `FROM node:18 as base`- your node:18 layers will all be cached so if a security update comes out you're in trouble.

This is also well known- if you google "why not to use docker build cache" you'll see all sorts of agreement. It's an extremely bad practice.

**Comment by Jomik** [comment]
> why not to use docker build cache

I actually thought it would be checking if there was a later image on the tag?
We just want to cache the result of the `npm run build` command, so long as the layers before are the same.
So if the `node:18` image changes, it should invalidate the cache.
I guess we could avoid it by using a sha instead of a version tag and then let renovate update it? 🤔

**Comment by tedivm** [comment]
If you change `node:18` to `node:20` it'll change the cache. If you keep `node:18` and a security release for `node:18` comes out you will keep the cache and lose the release.

**Comment by Jomik** [comment]
I'll have to test that, I was sure it checked, since I've seen it fetch metadata for the tags when it uses the cache. So figured it'd invalidate it if the sha changes.

**Pull request merged**
